#pragma once

#include <d3d.h>

class StubDirectDrawSurface7;

class StubDirect3DDevice7 : public IDirect3DDevice7 {
    int refCount = 1;
    D3DDEVICEDESC7 fakeDesc = {};

    bool contextAcquired = false;
    StubDirectDrawSurface7* boundTextures[8] = {};

    DWORD srcBlend = 2; // D3DBLEND_ONE
    DWORD dstBlend = 1; // D3DBLEND_ZERO
    bool alphaBlendEnabled = false;
    bool alphaTestEnabled = false;
    DWORD alphaRef = 0;
    DWORD textureFactor = 0xFFFFFFFF;
    bool zEnabled = true;
    bool zWriteEnabled = true;
    DWORD zFunc = D3DCMP_LESSEQUAL;

    D3DMATRIX worldMatrix = {};
    D3DMATRIX viewMatrix = {};
    D3DMATRIX projMatrix = {};
    D3DVIEWPORT7 viewport = {};

    void EnsureContext();
    void InitIdentityMatrix(D3DMATRIX& m);

public:
    StubDirect3DDevice7();

    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID, void** ppv) override;
    ULONG   STDMETHODCALLTYPE AddRef() override;
    ULONG   STDMETHODCALLTYPE Release() override;

    HRESULT STDMETHODCALLTYPE GetCaps(LPD3DDEVICEDESC7) override;
    HRESULT STDMETHODCALLTYPE EnumTextureFormats(LPD3DENUMPIXELFORMATSCALLBACK, LPVOID) override;
    HRESULT STDMETHODCALLTYPE BeginScene() override;
    HRESULT STDMETHODCALLTYPE EndScene() override;
    HRESULT STDMETHODCALLTYPE GetDirect3D(IDirect3D7**) override;
    HRESULT STDMETHODCALLTYPE SetRenderTarget(LPDIRECTDRAWSURFACE7, DWORD) override;
    HRESULT STDMETHODCALLTYPE GetRenderTarget(LPDIRECTDRAWSURFACE7*) override;
    HRESULT STDMETHODCALLTYPE Clear(DWORD, LPD3DRECT, DWORD, D3DCOLOR, D3DVALUE, DWORD) override;
    HRESULT STDMETHODCALLTYPE SetTransform(D3DTRANSFORMSTATETYPE, LPD3DMATRIX) override;
    HRESULT STDMETHODCALLTYPE GetTransform(D3DTRANSFORMSTATETYPE, LPD3DMATRIX) override;
    HRESULT STDMETHODCALLTYPE SetViewport(LPD3DVIEWPORT7) override;
    HRESULT STDMETHODCALLTYPE MultiplyTransform(D3DTRANSFORMSTATETYPE, LPD3DMATRIX) override;
    HRESULT STDMETHODCALLTYPE GetViewport(LPD3DVIEWPORT7) override;
    HRESULT STDMETHODCALLTYPE SetMaterial(LPD3DMATERIAL7) override;
    HRESULT STDMETHODCALLTYPE GetMaterial(LPD3DMATERIAL7) override;
    HRESULT STDMETHODCALLTYPE SetLight(DWORD, LPD3DLIGHT7) override;
    HRESULT STDMETHODCALLTYPE GetLight(DWORD, LPD3DLIGHT7) override;
    HRESULT STDMETHODCALLTYPE SetRenderState(D3DRENDERSTATETYPE, DWORD) override;
    HRESULT STDMETHODCALLTYPE GetRenderState(D3DRENDERSTATETYPE, LPDWORD) override;
    HRESULT STDMETHODCALLTYPE BeginStateBlock() override;
    HRESULT STDMETHODCALLTYPE EndStateBlock(LPDWORD) override;
    HRESULT STDMETHODCALLTYPE PreLoad(LPDIRECTDRAWSURFACE7) override;
    HRESULT STDMETHODCALLTYPE DrawPrimitive(D3DPRIMITIVETYPE, DWORD, LPVOID, DWORD, DWORD) override;
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitive(D3DPRIMITIVETYPE, DWORD, LPVOID, DWORD, LPWORD, DWORD, DWORD) override;
    HRESULT STDMETHODCALLTYPE SetClipStatus(LPD3DCLIPSTATUS) override;
    HRESULT STDMETHODCALLTYPE GetClipStatus(LPD3DCLIPSTATUS) override;
    HRESULT STDMETHODCALLTYPE DrawPrimitiveStrided(D3DPRIMITIVETYPE, DWORD, LPD3DDRAWPRIMITIVESTRIDEDDATA, DWORD, DWORD) override;
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitiveStrided(D3DPRIMITIVETYPE, DWORD, LPD3DDRAWPRIMITIVESTRIDEDDATA, DWORD, LPWORD, DWORD, DWORD) override;
    HRESULT STDMETHODCALLTYPE DrawPrimitiveVB(D3DPRIMITIVETYPE, LPDIRECT3DVERTEXBUFFER7, DWORD, DWORD, DWORD) override;
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitiveVB(D3DPRIMITIVETYPE, LPDIRECT3DVERTEXBUFFER7, DWORD, DWORD, LPWORD, DWORD, DWORD) override;
    HRESULT STDMETHODCALLTYPE ComputeSphereVisibility(LPD3DVECTOR, LPD3DVALUE, DWORD, DWORD, LPDWORD) override;
    HRESULT STDMETHODCALLTYPE GetTexture(DWORD, LPDIRECTDRAWSURFACE7*) override;
    HRESULT STDMETHODCALLTYPE SetTexture(DWORD, LPDIRECTDRAWSURFACE7) override;
    HRESULT STDMETHODCALLTYPE GetTextureStageState(DWORD, D3DTEXTURESTAGESTATETYPE, LPDWORD) override;
    HRESULT STDMETHODCALLTYPE SetTextureStageState(DWORD, D3DTEXTURESTAGESTATETYPE, DWORD) override;
    HRESULT STDMETHODCALLTYPE ValidateDevice(LPDWORD) override;
    HRESULT STDMETHODCALLTYPE ApplyStateBlock(DWORD) override;
    HRESULT STDMETHODCALLTYPE CaptureStateBlock(DWORD) override;
    HRESULT STDMETHODCALLTYPE DeleteStateBlock(DWORD) override;
    HRESULT STDMETHODCALLTYPE CreateStateBlock(D3DSTATEBLOCKTYPE, LPDWORD) override;
    HRESULT STDMETHODCALLTYPE Load(LPDIRECTDRAWSURFACE7, LPPOINT, LPDIRECTDRAWSURFACE7, LPRECT, DWORD) override;
    HRESULT STDMETHODCALLTYPE LightEnable(DWORD, BOOL) override;
    HRESULT STDMETHODCALLTYPE GetLightEnable(DWORD, BOOL*) override;
    HRESULT STDMETHODCALLTYPE SetClipPlane(DWORD, D3DVALUE*) override;
    HRESULT STDMETHODCALLTYPE GetClipPlane(DWORD, D3DVALUE*) override;
    HRESULT STDMETHODCALLTYPE GetInfo(DWORD, LPVOID, DWORD) override;
};
