#pragma once

#include <d3d.h>

class StubDirect3D7 : public IDirect3D7 {
    int refCount = 1;

public:
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID, void** ppv) override;
    ULONG   STDMETHODCALLTYPE AddRef() override;
    ULONG   STDMETHODCALLTYPE Release() override;

    HRESULT STDMETHODCALLTYPE EnumDevices(LPD3DENUMDEVICESCALLBACK7, LPVOID) override;
    HRESULT STDMETHODCALLTYPE CreateDevice(REFCLSID, LPDIRECTDRAWSURFACE7, LPDIRECT3DDEVICE7*) override;
    HRESULT STDMETHODCALLTYPE CreateVertexBuffer(LPD3DVERTEXBUFFERDESC, LPDIRECT3DVERTEXBUFFER7*, DWORD) override;
    HRESULT STDMETHODCALLTYPE EnumZBufferFormats(REFCLSID, LPD3DENUMPIXELFORMATSCALLBACK, LPVOID) override;
    HRESULT STDMETHODCALLTYPE EvictManagedTextures() override;
};
